### ISSUE TITLE
Saving selected checkbox throws error

### ISSUE THREAD

**Issue by timblack1** [TurboGears/sprox#5]
When I try to save a selected checkbox using TurboGears' tgext.admin.controller.AdminController, I get the following validation message:  "Please provide only one value."  The cause appears to be that https://github.com/TurboGears/sprox/blob/master/sprox/widgets/tw1widgets/templates/checkbox.html#L7 outputs a hidden input with a "name" attribute identical to the checkbox's name.  What should I do to avoid this error?

**Comment by amol-** [comment]
I suppose the second field was there to provide the false value when the first was not selected (as checkboxes do not submit any value when unselected) but we mostly inherited it as is, so I cannot take it for sure.

TW1 support is available mostly for historical reason and unmantained, projects are expected to switch to TW2 which is now the supported form generation library.

**Comment by timblack1** [comment]
Since I'm not upgrading this app to TW2 yet, I added the following script right after the two inputs to avoid the error:

```html
<script type="text/javascript">
var cb = document.querySelector("input[type=checkbox]#${id}")
var hidden_input = document.querySelector("input[type=hidden]#${id}")
function set_hidden_input_state(){
	if (!cb.checked){
		hidden_input.disabled = false;
		hidden_input.value = "False";
	}else{
		hidden_input.value = "True";
		hidden_input.disabled = true;
	}
}
set_hidden_input_state();
cb.addEventListener("click", set_hidden_input_state)
</script>
```
